OrdererOrgs:
  - Name: Orderer
    Domain: alcor.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: org1.alcor.com
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.alcor.com
    Template:
      Count: 2
    Users:
      Count: 1
