OrdererOrgs:
  - Name: Orderer
    Domain: yx.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: org1.yx.com
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.yx.com
    Template:
      Count: 1
    Users:
      Count: 1
